"""Protocol interfaces for ARGUS platform structural typing."""
from typing import Protocol, Any, List, Optional


class IMessageBus(Protocol):
    async def subscribe(self, topic: str, handler: Any) -> None: ...
    async def unsubscribe(self, topic: str, handler: Any) -> None: ...
    async def publish(self, topic: str, message: Any) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...


class IBlackboard(Protocol):
    async def write(self, section: Any, key: str, value: Any, agent_id: str) -> None: ...
    async def read(self, section: Any, key: str) -> Optional[Any]: ...
    async def read_section(self, section: Any) -> dict: ...
    async def delete(self, section: Any, key: str) -> bool: ...
    async def clear_section(self, section: Any) -> None: ...
    async def get_snapshot(self) -> dict: ...


class IRegistry(Protocol):
    async def register(self, agent: Any) -> None: ...
    async def deregister(self, agent_id: str) -> None: ...
    async def get(self, agent_id: str) -> Optional[Any]: ...
    async def get_all(self) -> List[Any]: ...
    async def find_by_capability(self, capability: str) -> List[Any]: ...
    async def update_health(self, agent_id: str, health: Any) -> None: ...
    async def update_load(self, agent_id: str, load: int) -> None: ...
    async def check_heartbeats(self) -> None: ...


class IOrchestrator(Protocol):
    async def submit_task(self, task: Any) -> str: ...
    async def cancel_task(self, task_id: str) -> bool: ...
    async def get_task_status(self, task_id: str) -> Any: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...


class IMemoryStore(Protocol):
    async def get(self, key: str) -> Optional[Any]: ...
    async def set(self, key: str, value: Any) -> None: ...
    async def delete(self, key: str) -> bool: ...
    async def clear(self) -> None: ...


class ISecurityProvider(Protocol):
    async def verify_token(self, token: str) -> Any: ...
    async def check_permission(self, role: str, resource: str, action: str) -> bool: ...
    async def detect_injection(self, text: str) -> tuple[bool, float, List[str]]: ...
