import React from 'react';
import { Card } from '../../components/Card';

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-12">
      <div>
        <h1 className="text-3xl font-semibold tracking-tight text-slate-900 dark:text-white mb-2">
          Terms & Conditions
        </h1>
        <p className="text-slate-500">Effective Date: {new Date().toLocaleDateString()}</p>
      </div>

      <Card className="p-8 space-y-6 text-sm text-slate-700 dark:text-slate-300">
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">1. Nature of the Software</h2>
          <p>
            ARGUS is a research demonstration and experimental software platform. It is provided strictly for academic, research, and evaluation purposes. 
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">2. No Production Security Guarantees</h2>
          <p>
            ARGUS is not a commercial enterprise security product. It does not provide real-time network protection, intrusion prevention, or guaranteed threat detection. The predictions, explanations, and risk scores generated by the models are experimental and may contain inaccuracies. Users must not rely on ARGUS as the sole mechanism for securing production infrastructure.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">3. Liability</h2>
          <p>
            The software is provided "as is", without warranty of any kind, express or implied. The authors and maintainers shall not be liable for any claims, damages, or other liabilities arising from the use of this software or reliance on its analytical outputs.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">4. Acceptable Use</h2>
          <p>
            Users agree to use ARGUS only with network data they are authorized to analyze. Users must not utilize the platform to reverse-engineer adversarial models for malicious purposes or violate any applicable regulations governing network data privacy.
          </p>
        </section>
      </Card>
    </div>
  );
}
