import os, time, json
from pathlib import Path
from typing import List, Dict, Union, Any, Optional

import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

# 1. Environment & Configuration Constants
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PROMPT_PATH = str(PROJECT_ROOT / "prompts/decision_support_system_prompt.txt")

DETECTOR_API_URL = os.getenv("DETECTOR_API_URL", "http://localhost:8000/predict")
OLLAMA_API_URL = os.getenv("OLLAMA_API_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2")
PROMPT_PATH = os.getenv("PROMPT_PATH", DEFAULT_PROMPT_PATH)

system_prompt_text = ""

def load_system_prompt() -> str:
    """Loads system prompt from separate text file without hardcoding."""
    global system_prompt_text
    prompt_file = Path(PROMPT_PATH)
    if not prompt_file.exists():
        raise FileNotFoundError(f"System prompt file not found at: {PROMPT_PATH}")
    with open(prompt_file, "r", encoding="utf-8") as f:
        system_prompt_text = f.read().strip()
    return system_prompt_text

# Load system prompt at module initialization
load_system_prompt()

# 2. Pydantic Request & Response Schemas
class FlowRecord(BaseModel):
    pkt_mean_to_max: float = Field(..., description="Ratio of mean packet length to max packet length [0,1]")
    tcp_flag_density: float = Field(..., description="TCP flag multiplicity count")
    log_pkt_mean: float = Field(..., description="Log-transformed mean packet length")
    log_pkt_max: float = Field(..., description="Log-transformed max packet length")

    model_config = {
        "json_schema_extra": {
            "example": {
                "pkt_mean_to_max": 0.95,
                "tcp_flag_density": 1.0,
                "log_pkt_mean": 4.2,
                "log_pkt_max": 4.3
            }
        }
    }

class LatencyBreakdown(BaseModel):
    detector_ms: float = Field(..., description="Detector model inference latency in milliseconds")
    llm_ms: float = Field(..., description="Ollama LLM decision support latency in milliseconds")
    total_ms: float = Field(..., description="Total end-to-end processing latency in milliseconds")

class ExplanationItem(BaseModel):
    prediction: int = Field(..., description="Binary detection label (1=Attack, 0=Benign)")
    probability: float = Field(..., description="Continuous attack probability score")
    threshold: float = Field(..., description="Decision threshold (default: 0.50)")
    shap_values: Dict[str, float] = Field(..., description="Per-feature SHAP contribution values")
    explanation_text: str = Field(..., description="Human-readable decision support explanation generated by Ollama LLM")
    latency_ms: LatencyBreakdown = Field(..., description="Detailed latency breakdown for computational efficiency evaluation")

class ExplanationResponse(BaseModel):
    explanations: List[ExplanationItem]

# 3. FastAPI Service Definition
app = FastAPI(
    title="ARGUS Decision Support & Explainability Agent",
    description="FastAPI agent wrapping local detector API and local Ollama LLM for human-readable SHAP explanation.",
    version="1.0.0"
)

@app.get("/health")
def health_check():
    """Health check endpoint for decision support agent."""
    prompt_loaded = bool(system_prompt_text)
    return {
        "status": "healthy",
        "detector_api_url": DETECTOR_API_URL,
        "ollama_api_url": OLLAMA_API_URL,
        "ollama_model": OLLAMA_MODEL,
        "system_prompt_loaded": prompt_loaded,
        "prompt_path": PROMPT_PATH
    }

def generate_llm_explanation(prediction: int, probability: float, shap_values: Dict[str, float]) -> str:
    """
    Sends SHAP context to local Ollama API (http://localhost:11434/api/generate).
    Falls back gracefully to a structured fallback explanation if Ollama is unreachable.
    """
    user_prompt = f"""
Model Prediction Context:
- Binary Prediction: {prediction} ({'Attack Alert' if prediction == 1 else 'Benign Telemetry'})
- Probability Score: {probability:.6f} (Decision Threshold: 0.50)
- SHAP Feature Contribution Values:
  * pkt_mean_to_max: {shap_values.get('pkt_mean_to_max', 0.0):.6f}
  * tcp_flag_density: {shap_values.get('tcp_flag_density', 0.0):.6f}
  * log_pkt_mean: {shap_values.get('log_pkt_mean', 0.0):.6f}
  * log_pkt_max: {shap_values.get('log_pkt_max', 0.0):.6f}

Please generate a concise, human-readable decision support explanation for the SOC analyst.
"""

    payload = {
        "model": OLLAMA_MODEL,
        "system": system_prompt_text,
        "prompt": user_prompt,
        "stream": False,
        "options": {
            "temperature": 0.2,
            "max_tokens": 200
        }
    }

    try:
        url = f"{OLLAMA_API_URL.rstrip('/')}/api/generate"
        response = requests.post(url, json=payload, timeout=10.0)
        if response.status_code == 200:
            res_data = response.json()
            explanation = res_data.get("response", "").strip()
            if explanation:
                return explanation
    except Exception as e:
        print(f"[!] Ollama LLM call warning ({url}): {e}")

    # Fallback explanation if local Ollama service is offline/not running
    verdict_str = "ATTACK ALERT" if prediction == 1 else "BENIGN TRAFFIC"
    top_driver = max(shap_values.items(), key=lambda x: abs(x[1]))
    direction = "increasing attack probability" if top_driver[1] > 0 else "reducing attack probability"
    
    return (
        f"[{verdict_str}] Detector assigned a probability of {probability:.4f} (threshold 0.50). "
        f"The primary feature driver is '{top_driver[0]}' with a SHAP score of {top_driver[1]:+.4f}, "
        f"substantially {direction}. "
        f"(Note: Local Ollama LLM '{OLLAMA_MODEL}' was offline; structured fallback generated)."
    )

@app.post("/explain", response_model=ExplanationResponse)
def explain(payload: Union[List[FlowRecord], FlowRecord, Dict[str, Any]]):
    """
    POST /explain endpoint.
    1. Calls local detector API (POST http://localhost:8000/predict) to retrieve predictions & SHAP values.
    2. Measures detector latency.
    3. Formats prompt & queries local Ollama LLM to generate human-readable explanation.
    4. Measures LLM latency.
    5. Returns prediction, probability, SHAP values, explanation text, and latency breakdown.
    """
    t_start_total = time.perf_counter()

    # Parse input into list of FlowRecord objects
    if isinstance(payload, FlowRecord):
        records = [payload]
    elif isinstance(payload, list):
        records = payload
    elif isinstance(payload, dict) and "records" in payload:
        records = [FlowRecord(**r) for r in payload["records"]]
    elif isinstance(payload, dict):
        records = [FlowRecord(**payload)]
    else:
        raise HTTPException(status_code=400, detail="Invalid request payload format.")

    if not records:
        raise HTTPException(status_code=400, detail="No flow records provided.")

    # 1. Call Detector API & Measure Detector Latency
    t0_det = time.perf_counter()
    detector_payload = [r.model_dump() for r in records]
    
    try:
        det_response = requests.post(DETECTOR_API_URL, json=detector_payload, timeout=5.0)
        if det_response.status_code != 200:
            raise HTTPException(
                status_code=502,
                detail=f"Detector API returned error status {det_response.status_code}: {det_response.text}"
            )
        det_data = det_response.json()
    except requests.exceptions.RequestException as e:
        raise HTTPException(
            status_code=503,
            detail=f"Failed to connect to Detector API at {DETECTOR_API_URL}: {str(e)}"
        )
    t1_det = time.perf_counter()
    detector_latency_ms = (t1_det - t0_det) * 1000.0

    predictions_list = det_data.get("predictions", [])
    if len(predictions_list) != len(records):
        raise HTTPException(status_code=500, detail="Detector returned invalid predictions length mismatch.")

    explanations = []
    
    # 2. Call Ollama LLM for each prediction & Measure LLM Latency
    for item in predictions_list:
        pred = item["prediction"]
        prob = item["probability"]
        th = item.get("threshold", 0.50)
        shap_vals = item["shap_values"]

        t0_llm = time.perf_counter()
        explanation_txt = generate_llm_explanation(pred, prob, shap_vals)
        t1_llm = time.perf_counter()
        llm_latency_ms = (t1_llm - t0_llm) * 1000.0

        t_total_ms = (time.perf_counter() - t_start_total) * 1000.0

        explanations.append(ExplanationItem(
            prediction=pred,
            probability=prob,
            threshold=th,
            shap_values=shap_vals,
            explanation_text=explanation_txt,
            latency_ms=LatencyBreakdown(
                detector_ms=round(detector_latency_ms / len(records), 2),
                llm_ms=round(llm_latency_ms, 2),
                total_ms=round(t_total_ms, 2)
            )
        ))

    return ExplanationResponse(explanations=explanations)
