import os

markdown = """# ARGUS Scientific Validation Provenance

## Existing Baseline Identification

### A. Experiment Source
The primary published cross-domain numbers (F1=0.3869, MCC=0.1205, FPR=87.08% for IEC104 Target) were generated by the **Phase 4 Full ARGUS Pipeline** with Prior Correction and Multi-Source Model Fusion (Experiment ID: `E5_fusion_CORAL_prior`).

### B. Dataset Split Used
Target domain testing is evaluated purely on the strictly frozen, class-stratified split:
`ARGUS_Cross_Domain_Results/argus_coral_data/iec104_test_features.csv`
- Number of test samples: 714,453

### C. Checkpoints
- LightGBM Models trained on D1 and D2 Source data (with CORAL alignment).

### D. Features
4-feature tuple: `['pkt_mean_to_max', 'tcp_flag_density', 'log_pkt_mean', 'log_pkt_max']`

### E. Threshold
- Threshold used: `0.50` (Calibrated on Target Calibration split).

### F. Available Predictions
- True Label (`y_true`) and Predicted Probability (`y_prob`) are preserved in `phase4_results/experiments/E5_fusion_CORAL_prior/predictions.csv`.
- Asset criticality is synthetically generated via the Risk Agent layer during runtime evaluation.
"""

os.makedirs('artifacts/reports', exist_ok=True)
with open('artifacts/reports/scientific_validation_provenance.md', 'w') as f:
    f.write(markdown)

print("Provenance generated.")
